### ISSUE TITLE
"Room pagination error: Error: Page size=50 cannot exceed initialSyncLimit=25"

### ISSUE THREAD

**Issue by freakontrol** [Skylar-Tech/node-red-contrib-matrix-chat#123]
Hi, as in the title, I cannot paginate more than 25, it this a node limit or is Matrix room settings related?
I'm currently using the Paginate Room node to provide the chat history to an LLM, but I cannot retrieve all the history.
Maybe my approach is wrong.
BTW very good project :) , waiting for the next release with #118 to be solved.

**Comment by skylord123** [comment]
Hi and thanks for the kind words,

Regarding the limitation on paginating more than 25 events:

When we initialize the `matrixClient`, we currently hardcode the `initialSyncLimit` option to 25. This option determines how many events are retrieved when you first join a room. The default value in the `matrix-js-sdk` is 10, which was our initial setting before adding the Paginate Room node.

During testing of the Paginate Room node, I discovered that you cannot request more events than the number specified in the `initialSyncLimit` option. This is why I increased it to 25 to provide a more generous range. While the default for the Synapse server is set to 100 (as mentioned [here](https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#filter_timeline_limit)), many providers, such as matrix.org, may set it lower, which is why I chose 25 for now.

We could make the `initialSyncLimit` configurable in the next release. My concern is that users might input a very large number without understanding the potential impact, such as increased memory usage or slower performance. I'll consider how to make this option available while clearly communicating the consequences in the UI.

> I'm currently using the Paginate Room node to provide the chat history to an LLM, but I cannot retrieve all the history.
Maybe my approach is wrong.

Your approach is probably correct, but the limitation is due to the `initialSyncLimit` setting as explained above.

I apologize for releasing the version without proper examples for all nodes. I've already addressed this for the next release, and you can find the examples in the examples folder on the `dev` branch here:

[Examples Folder](https://github.com/Skylar-Tech/node-red-contrib-matrix-chat/blob/dev/examples/README.md)

Here's an example flow for paginating room history (found under `Paginate the entire history of a given room` on the examples):

![Paginate Room History Example](https://github.com/Skylar-Tech/node-red-contrib-matrix-chat/blob/dev/examples/paginate-room-history.png?raw=true)

**Explanation:**

When you use the Paginate Room node, it utilizes a `Pagination Key` (which defaults to `msg.paginateKey`). If you provide this key, it will use it; otherwise, it generates one randomly and sets it to the defined Pagination Key variable from the config page. This key is used to create a new `TimelineWindow` associated with it.

To fetch subsequent pages of events, you need to pass the same `Pagination Key` back into the Paginate Room node. This ensures that the same `TimelineWindow` is used for pagination. Keep in mind that deploying flows deletes existing `TimelineWindows`, so pagination will start over.

Events fetched through pagination are saved into storage, so re-paginating the same events should avoid hitting the server until you reach events not stored locally. Note that leaving a room deletes all associated events from local storage.

So you will need to page through events with 25 max per page currently. This is exactly how Element works when you scroll back through history on a room (except I believe Element uses a limit of something like 8 events at a time). You may also need to use some sort of delay system so you aren't slamming the server too much as I am sure matrix.org and other providers throttle this, but if you host your own server this really isn't an issue. Since I host my own server on my local network and my user has special privileges I just slam it without any delay.



Let me know if this helps or if you have any further questions.

**Comment by skylord123** [comment]
It's also good to note that if your room history gets very large it can start making every deploy/node-red startup hang for a bit while it parses the local history.

I noticed when I had my bot join the public matrix room it was causing NR to take 30 seconds to deploy/startup. So be wary that pulling a lot of history can negatively impact things.

We may need to add something that lets us manage our local storage.

**Comment by freakontrol** [comment]
Hi thank you for the detailed explanation, yes I agree that retrieving every time the history from matrix is not a good approach when scaling with more rooms and users ecc. 
A sort of local cache can help.

If I have spare time I can try to write a function for that, writing the history in a file or using a DB (overkill?) but I'm no experienced in NodeRed.

For now I will try your example, again thank you for your work.
