### ISSUE TITLE
Not seeing a room invitation behind the "receive" node

### ISSUE THREAD

**Issue by jacotec** [Skylar-Tech/node-red-contrib-matrix-chat#70]
It looks like there's an issue with the receive node.

I need to perform some action when the user to which the plugin is connected is invited in to a room:

- Joining the room
- Issue a command in the room
- Invite other users into the room

The actions are not the problem - but I'm not getting the invitation? Connecting a debug to the receive node, simply nothing happens.

When I set the client to "auto join rooms", I'm getting the last message as a payload - but no indication that the room was freshly joined.

Do I overlook something, or is this a bug?

**Comment by jacotec** [comment]
I've submitted a pull request #71 which solves this.

**Comment by skylord123** [comment]
I accepted your PR and changed it up a bit so it is now it's own node. It didn't quite match the same outputs as the receive node and will be easier to use out of the box. It was also receiving old events so that is now fixed. I also added a node for leaving a room.

This will be released here soon.

Thanks!

**Comment by jacotec** [comment]
@skylord123 Cool, thanks! That's the most clean way (but I don't have the experience to create new nodes).

I'm looking forward to it!

BTW: Is there any way to change/set a room name via node-red?

**Comment by skylord123** [comment]
[set-room-name-or-topic.json.txt](https://github.com/Skylar-Tech/node-red-contrib-matrix-chat/files/10168059/set-room-name-or-topic.json.txt)

^ import that in Node-RED. Once imported edit the function Node's first line to match the user ID of your matrix client.

You have raw access to the matrixClient using these function nodes and can call any of the methods from the matrix-js-sdk client.ts file found here: https://github.com/matrix-org/matrix-js-sdk/blob/master/src/client.ts#L3713

All I did was take the example function from our examples on here and modified it to use the method `setRoomName` from matrix.ts. There was also a `setRoomTopic` so I also included an example for that.

So you can almost do whatever you want using these function nodes since the client is exposed there.

**Comment by skylord123** [comment]
This is now live on version v0.7.0. Thanks!
